# Generated by Django 4.2.7 on 2023-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('passw', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
