# Generated by Django 4.2.7 on 2023-11-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_pelicula_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='peliculas',
            field=models.ManyToManyField(to='user_auth.pelicula'),
        ),
    ]
