# Generated by Django 4.2.6 on 2023-10-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plataforma_videojuego_disponibilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plataforma',
            options={'ordering': ['nombre']},
        ),
    ]
