# Generated by Django 4.2.6 on 2023-10-30 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_plataforma_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videojuego',
            options={'ordering': ['titulo', '-unidades'], 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AddField(
            model_name='plataforma',
            name='existencias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
