# Generated by Django 4.2.6 on 2023-11-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_plataforma_options_alter_videojuego_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copia',
            old_name='alquilada',
            new_name='alquilado',
        ),
    ]
