# Generated by Django 4.2.6 on 2023-11-06 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_rename_alquilada_copia_alquilado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='videojuego',
        ),
        migrations.AddField(
            model_name='copia',
            name='plataforma',
            field=models.ManyToManyField(related_name='copias_plataforma', to='main.videojuego'),
        ),
        migrations.AlterField(
            model_name='copia',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='copia',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copias_videojuego', to='main.videojuego'),
        ),
    ]
