# Generated by Django 4.2.6 on 2023-11-06 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_plataforma_videojuego_copia_plataforma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copia',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='cantidad',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataforma',
            field=models.ManyToManyField(to='main.plataforma'),
        ),
        migrations.AlterField(
            model_name='copia',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='copia',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videojuego'),
        ),
    ]
