# Generated by Django 4.2.6 on 2023-11-10 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_plataforma_plataforma_videojuego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sony', max_length=255, verbose_name='Nombre')),
                ('fabricante', models.CharField(default='Sony', max_length=255, verbose_name='Fabricante')),
                ('fecha_lanzamiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de lanzamiento')),
                ('precio', models.DecimalField(decimal_places=2, default='12', max_digits=10, verbose_name='Precio')),
                ('plataforma', models.CharField(default='Sony', max_length=255, verbose_name='Plataforma')),
            ],
            options={
                'verbose_name': 'Consola',
                'verbose_name_plural': 'Consolas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sony', max_length=255, verbose_name='Nombre')),
                ('direccion', models.CharField(default='Sony', max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(default='Sony', max_length=255, verbose_name='Teléfono')),
                ('nif', models.CharField(default='Sony', max_length=255, verbose_name='NIF')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AlterModelOptions(
            name='copia',
            options={'verbose_name': 'Copia', 'verbose_name_plural': 'Copias'},
        ),
        migrations.AlterModelOptions(
            name='videojuego',
            options={'verbose_name': 'Videojuego', 'verbose_name_plural': 'Videojuegos'},
        ),
        migrations.RemoveField(
            model_name='copia',
            name='alquilado',
        ),
        migrations.RemoveField(
            model_name='copia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='copia',
            name='fecha_alquiler',
        ),
        migrations.RemoveField(
            model_name='copia',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='copia',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('dañado', 'Dañado'), ('perdido', 'Perdido')], default='nuevo', max_length=255, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='copia',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de compra'),
        ),
        migrations.AddField(
            model_name='copia',
            name='numero_serie',
            field=models.CharField(default='000', max_length=255, verbose_name='Número de serie'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='fecha_lanzamiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(default='Accion', max_length=255, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(default='PS5', max_length=255, verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default='20', max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='copia',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videojuego', verbose_name='Videojuego'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(default='Spiderman', max_length=255, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='Plataforma',
        ),
    ]
