# Generated by Django 4.2.6 on 2023-11-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_consola_empresa_alter_copia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='fabricante',
            field=models.CharField(max_length=255, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='fecha_lanzamiento',
            field=models.DateField(verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='plataforma',
            field=models.CharField(max_length=255, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='copia',
            name='fecha_compra',
            field=models.DateField(verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='copia',
            name='numero_serie',
            field=models.CharField(max_length=255, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nif',
            field=models.CharField(max_length=255, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='fecha_lanzamiento',
            field=models.DateField(verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(max_length=255, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(max_length=255, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
