# Generated by Django 4.2.6 on 2023-10-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videojuego',
            options={'ordering': ['titulo', '-unidades']},
        ),
    ]
