# Generated by Django 4.2.6 on 2023-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_videojuego_options_plataforma_existencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='existencias',
            field=models.IntegerField(default=1),
        ),
    ]
