# Generated by Django 4.2.6 on 2023-11-06 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alquilada', models.BooleanField()),
                ('fecha_alquiler', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videojuego')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
