# Generated by Django 4.2.6 on 2023-11-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_copia_plataforma_videojuego_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='plataforma',
            field=models.ManyToManyField(to='main.videojuego'),
        ),
    ]
