# Generated by Django 4.2.6 on 2023-11-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_videojuego_plataforma_plataforma_plataforma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='plataforma',
            new_name='videojuego',
        ),
    ]
