# Generated by Django 4.2.6 on 2023-11-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_consola_fabricante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad_C',
            fields=[
                ('numero_serie', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de serie')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('dañado', 'Dañado'), ('perdido', 'Perdido')], default='nuevo', max_length=255, verbose_name='Estado')),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.consola', verbose_name='Consola')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Unidad_V',
            fields=[
                ('numero_serie', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de serie')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('dañado', 'Dañado'), ('perdido', 'Perdido')], default='nuevo', max_length=255, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Copia',
                'verbose_name_plural': 'Copias',
            },
        ),
        migrations.AddField(
            model_name='videojuego',
            name='iframe_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(default='juego.png', upload_to='videojuegos'),
        ),
        migrations.DeleteModel(
            name='Copia',
        ),
        migrations.AddField(
            model_name='unidad_v',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videojuego', verbose_name='Videojuego'),
        ),
    ]
